# Generated by Django 5.2.6 on 2025-09-26 23:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroPendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('matricula', models.CharField(max_length=50, unique=True)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('comprovante_matricula', models.FileField(blank=True, null=True, upload_to='comprovantes/')),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('status_validacao', models.CharField(choices=[('Pendente', 'Pendente'), ('Rejeitado', 'Rejeitado')], default='Pendente', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AlunoAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('matricula', models.CharField(max_length=50, unique=True)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_vencimento_assinatura', models.DateField()),
                ('tipo_carteirinha', models.CharField(choices=[('Digital', 'Digital'), ('Física', 'Física')], max_length=10)),
                ('status_pagamento', models.CharField(choices=[('Pago', 'Pago'), ('Pendente', 'Pendente'), ('Vencido', 'Vencido')], default='Pendente', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
