# Generated by Django 5.2.6 on 2025-09-27 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno_email', models.EmailField(max_length=254)),
                ('assunto', models.CharField(max_length=255)),
                ('descricao_problema', models.TextField()),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('data_fechamento', models.DateTimeField(blank=True, null=True)),
                ('status_ticket', models.CharField(choices=[('Aberto', 'Aberto'), ('Em Andamento', 'Em Andamento'), ('Fechado', 'Fechado')], default='Aberto', max_length=20)),
                ('resposta_equipe', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
