# Generated by Django 5.2.6 on 2025-09-27 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('endereco', models.CharField(max_length=255)),
                ('categoria', models.CharField(max_length=100)),
                ('descricao_beneficio', models.TextField()),
                ('regras_de_uso', models.TextField()),
                ('status_parceria', models.CharField(choices=[('Ativa', 'Ativa'), ('Inativa', 'Inativa')], default='Ativa', max_length=10)),
            ],
        ),
    ]
