# Generated by Django 5.2.6 on 2025-09-27 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parceiros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropostaParceria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('endereco', models.CharField(max_length=255)),
                ('categoria', models.CharField(max_length=100)),
                ('descricao_beneficio', models.TextField()),
                ('email_contato', models.EmailField(max_length=254)),
                ('data_proposta', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovada', 'Aprovada'), ('Rejeitada', 'Rejeitada')], default='Pendente', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='regras_de_uso',
            field=models.TextField(blank=True),
        ),
    ]
